import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError, retry, switchMap } from 'rxjs/operators';
import { ObjectG, TypeObject } from '../pages/object/object.model';
import { AuthService } from '../pages/authentication/side-login/login-choice/auth.service';

@Injectable({
  providedIn: 'root'
})
export class ObjectService {
  private apiUrl = 'http://localhost:8088/api/v1/object';

  constructor(
    private http: HttpClient,
    private authService: AuthService
  ) {}

  private addAuthHeaders(): { headers: HttpHeaders } {
    const headers = new HttpHeaders();
    const token = localStorage.getItem('authToken');

    if (!token) {
      console.error('No token found in localStorage');
      // Try to get token from session storage as a fallback
      const sessionToken = sessionStorage.getItem('authToken');
      if (sessionToken) {
        console.log('Using token from sessionStorage');
        headers.set('Authorization', `Bearer ${sessionToken}`);
      } else {
        throw new Error('No authentication token found');
      }
    } else {
      console.log('Using token from localStorage');
      headers.set('Authorization', `Bearer ${token}`);
    }

    headers.set('Content-Type', 'application/json');

    return { headers };
  }

  private refreshToken(): Observable<any> {
    console.log('Refreshing token...');
    return this.authService.login({
      email: localStorage.getItem('email') || '',
      password: localStorage.getItem('password') || ''
    }).pipe(
      catchError(error => {
        console.error('Token refresh failed:', error);
        return throwError(error);
      })
    );
  }

  getAllObjects(): Observable<ObjectG[]> {
    return this.http.get<ObjectG[]>(`${this.apiUrl}/getall_object`, this.addAuthHeaders())
      .pipe(
        catchError(error => {
          console.error('Error fetching objects:', error);
          return throwError(error);
        })
      );
  }

  addObject(object: ObjectG): Observable<ObjectG> {
    try {
      // Remove the ID since it should be generated by the backend
      const newObject = { ...object };
      delete newObject.idGarantie;

      // Log the request payload for debugging
      console.log('Adding object:', newObject);

      return this.http.post<ObjectG>(`${this.apiUrl}/add_object`, newObject, this.addAuthHeaders())
        .pipe(
          retry({
            count: 1,
            delay: 1000
          }),
          catchError(error => {
            console.error('Error adding object:', error);
            if (error.status === 403) {
              console.error('Authentication error - token:', localStorage.getItem('token'));
              // Try to refresh the token
              return this.refreshToken().pipe(
                switchMap(() => {
                  // Retry the original request with the new token
                  return this.http.post<ObjectG>(`${this.apiUrl}/add_object`, newObject, this.addAuthHeaders());
                })
              );
            }
            return throwError(error);
          })
        );
    } catch (error) {
      console.error('Error preparing request:', error);
      return throwError(error);
    }
  }

  updateObject(object: ObjectG): Observable<ObjectG> {
    return this.http.put<ObjectG>(`${this.apiUrl}/update_object`, object, this.addAuthHeaders())
      .pipe(
        catchError(error => {
          console.error('Error updating object:', error);
          return throwError(error);
        })
      );
  }

  deleteObject(id: number): Observable<void> {
    return this.http.delete<void>(`${this.apiUrl}/remove_object/${id}`, this.addAuthHeaders())
      .pipe(
        catchError(error => {
          console.error('Error deleting object:', error);
          return throwError(error);
        })
      );
  }

  deactivateObject(id: number): Observable<ObjectG> {
    return this.http.put<ObjectG>(`${this.apiUrl}/${id}/deactivate`, {}, this.addAuthHeaders())
      .pipe(
        catchError(error => {
          console.error('Error deactivating object:', error);
          return throwError(error);
        })
      );
  }

  getPaginatedObjects(
    page: number = 0,
    size: number = 5,
    sortBy: 'ownershipCertifNumber' | 'estimatedValue' | 'type' = 'ownershipCertifNumber',
    direction: 'asc' | 'desc' = 'asc'
  ): Observable<any> {
    return this.http.get<any>(`${this.apiUrl}/paginated`, {
      params: {
        page: page.toString(),
        size: size.toString(),
        sortBy,
        direction
      },
      ...this.addAuthHeaders()
    })
      .pipe(
        catchError(error => {
          console.error('Error fetching paginated objects:', error);
          return throwError(error);
        })
      );
  }
}
