export interface Request {
  id_request?: number;  // Optional because it's generated by the backend
  date_Request: string;  // The request date in ISO string format (e.g. "2025-05-01")
  product: Product;  // The product associated with the request
  document: string;  // Document description
  user: any;  // You can specify the exact User model if needed
}

// Define the Product interface (if it's not already defined elsewhere in your code)
export enum Product {
  JAM3EYA = 'JAM3EYA',
  EPARGNE = 'EPARGNE',
  EPARGNE_ZEKET = 'EPARGNE_ZEKET'
}
